import { Module } from '@nestjs/common'
import { AppController } from './app.controller'
import { AppService } from './app.service'

/**
 * Standard module for the app.
 *
 * @remarks
 * This has been automatically generated by Nest.js
 *
 */
@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService]
})
export class AppModule {}
