import { NestFactory } from '@nestjs/core'

import { AppModule } from './app.module'

/**
 * Standard entry point for the Nest application.
 *
 * @remarks
 * This has been automatically generated by Nest.js
 *
 */
async function bootstrap() {
  const app = await NestFactory.create(AppModule)
  await app.listen(3000)
}
bootstrap()
