import { Module } from '@nestjs/common'
import { ServeStaticModule } from '@nestjs/serve-static'
import { join } from 'path'

import { AppController } from './app.controller'
import { AppService } from './app.service'

/**
 * Standard module for the app.
 *
 * @remarks
 * This has been automatically generated by Nest.js
 *
 */
@Module({
  imports: [
    ServeStaticModule.forRoot({
      rootPath: join(__dirname, '..', 'docs')
    })
  ],
  controllers: [AppController],
  providers: [AppService]
})
export class AppModule {}
