import { Controller, Get } from '@nestjs/common'

import { AppService } from './app.service'

/**
 * Standard controller for the app.
 *
 * @remarks
 * This has been automatically generated by Nest.js
 *
 */
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello()
  }
}
